### ISSUE TITLE
Design Informer API

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#137]
Design document: https://www.notion.so/codechain/Informer-API-a12a9456ca0a49d19bbbdd0c2b8c7bfe

**Comment by MSNTCS** [comment]
- Hot events

- [ ] Websocket + JSONRPC handler

- [ ] InformerService

- [ ] Relation between components

- [ ] Run an example

- Cold Events

**Comment by MSNTCS** [comment]
The whole structure of the informer API is addressed is the above-mentioned PRs. In order to complete the informer design to the all-in-all extent the future work is needed which will be discussed in later issues.
