### ISSUE TITLE
Remove Store and Remove Transaction

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#17]
Anyone can save any data in CodeChain using the Store transaction. They can also remove it by using the Remove transaction.

In Foundry, that can be done using the module system. Let's remove them.

**Comment by dynaxis** [comment]
The natural next step is just to deprecate relevant parameters. If we decide on removing all the deprecated parameters later altogether and filing another issue tracking it, I'll follow up with another simple PR to do the deprecations only. What do you all think?
