### ISSUE TITLE
Add snapshot synchronization

### ISSUE THREAD

**Issue by Remagpie** [CodeChain-io/foundry#23]
Snapshot synchronization was originally almost implemented in [`CodeChain/snapshot`](https://github.com/CodeChain-io/codechain/tree/snapshot) branch.
The blocking problems were related to asset timelocks, and since we're [stripping asset implementation](https://github.com/CodeChain-io/foundry/pull/11) in this repository, we just have to port the commits to this repository.

The following is the list of commits to be ported: 

* ~https://github.com/CodeChain-io/codechain/commit/18001f62d95923b26d6d902f57c3057ce8347862 Introduce on_open_block~ https://github.com/CodeChain-io/foundry/pull/27
* ~https://github.com/CodeChain-io/codechain/commit/3c8d9f0f8e8896cb61c4675a4824606027aecb49 Implement TrieDB::is_complete~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/1dff7e26673e94fd239adea436a63e67dae5690a Add complete_register to ConsensusEngine~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/fc6a3ded0dbdf36e7f79315f1af291b734fa2a72 Change waitNodeUntilTerm to return TermMetadata~ https://github.com/CodeChain-io/foundry/pull/22
* ~https://github.com/CodeChain-io/codechain/commit/80e6282d970aa4695acc9921395b056256deff84 Refactor rpc startup code~ https://github.com/CodeChain-io/foundry/pull/20
* ~https://github.com/CodeChain-io/codechain/commit/74c46d6a49ff8fb3f5126b269c491519bd40b26d Refactor send status function~ https://github.com/CodeChain-io/foundry/pull/22
* ~https://github.com/CodeChain-io/codechain/commit/ec0ef2b078f1d154654a0b5a9f112d1fd4f0174f Remove unnecessary cloning in block sync~ https://github.com/CodeChain-io/foundry/pull/22
* ~https://github.com/CodeChain-io/codechain/commit/06b3f97add242b8176af21ead2f0017aebc9e783 Enhance error message in waitForTermChange~ https://github.com/CodeChain-io/foundry/pull/22
* ~https://github.com/CodeChain-io/codechain/commit/3b9c38845db6b1c899d48d927dc07ce547dfe3fa Add term_params to Metadata~ https://github.com/CodeChain-io/foundry/pull/18
* ~https://github.com/CodeChain-io/codechain/commit/5c647379789399972224be60228ec47b093679e0 Snapshot term_metadata on every term close for the era > 0~ https://github.com/CodeChain-io/foundry/pull/18
* ~https://github.com/CodeChain-io/codechain/commit/7fba4f56a4899ba2b57777a529917b0560627010 Update the era with the value in current block's state~ Not related
* ~https://github.com/CodeChain-io/codechain/commit/9a6ec55eff39d5059a3865284b6e0a7140d4b36b Read term_params from the snapshot~ https://github.com/CodeChain-io/foundry/pull/18
* ~https://github.com/CodeChain-io/codechain/commit/1101c5b15968a206aff1e485a51c26893254714f Precalculate the fee in era=1~ https://github.com/CodeChain-io/foundry/pull/27
* ~https://github.com/CodeChain-io/codechain/commit/105166582863451acbd233d3125f1386166c2ae4 Remove outdated snapshot module~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/f718e4a6fe859cd5f15019cc18b0a49f3704ccb2 Add configuration option for the snapshot sync target~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/b3e22381d1a7a7a7219aa8c0f03385f321763f20 Decide the sync extension's state with the snapshot target~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/1b785d9a705fdd938e79b4b6898bb1b41f8902da Implement Snapshot & Restore modules~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/403b519902788768648ba7871ff8d1b60a516aae Fetch snapshot header from peers~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/f4af59869aaa7e7a4f949cb240013b3eaa91ed16 Make the snapshot header importable without parent~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/be3591491a6006e1da01e9778da5da9e6905c9df Update snapshot message format~ https://github.com/CodeChain-io/foundry/pull/28
* ~https://github.com/CodeChain-io/codechain/commit/a8627c208fd69bd954b0c4c632f8db13c157f314 Import only desired bootstrap headers~ https://github.com/CodeChain-io/foundry/pull/29
* ~https://github.com/CodeChain-io/codechain/commit/ecdaa3ad8133e8f4755dfb32b7495d14b70c00bb Implement snapshot service~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/27e3c4e173dd06f40a453289637c1938eea444b7 Add RPC devel_snapshot~ https://github.com/CodeChain-io/foundry/pull/20
* ~https://github.com/CodeChain-io/codechain/commit/ef1a176aa9e79dcac7bd90f7a0e9d690fe21e887 Add basic e2e test for snapshot~ https://github.com/CodeChain-io/foundry/pull/20
* ~https://github.com/CodeChain-io/codechain/commit/b3cc277dde37815d55a403db03b03d6d490e78d5 Rename total_score to nonce in sync message~ https://github.com/CodeChain-io/foundry/pull/28
* ~https://github.com/CodeChain-io/codechain/commit/443a17848232f6cf59a961abb20e426db3d28bae Add SnapshotNotifySender to Tendermint worker~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/4e5ba6b176c2c155a6c0d21aa0670bea6f82269b Implement snapshot on term end~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/7490d25a888e04b6e0e7e3640354397f8e696975 Add snapshot sync test with Tendermint dynamic validator~
* ~https://github.com/CodeChain-io/codechain/commit/6d5af4de7be89d1a5e839a47454a777bb3591311 Send and receive snapshot chunk requests~
* ~https://github.com/CodeChain-io/codechain/commit/fe9c7852e0a813ad069ce263bbdf7879091a4bb7 Serve snapshot responses to peers~
* https://github.com/CodeChain-io/codechain/commit/ef3ad4fc3de804c730c56e11fd71c2f5c4f37c41 Use binding for match clause
* ~https://github.com/CodeChain-io/codechain/commit/cbe8322b3f6c5ef930464368837ce20fd79b6d66 Add RPC snapshot_getList~ https://github.com/CodeChain-io/foundry/pull/20
* ~https://github.com/CodeChain-io/codechain/commit/af90610e7c632f92eadf008f5d7069a718e09d1d Add autoremoving expired snapshot feature~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/a96282de61253f90a3eb9d1a8f7b9c7b8788559f Detect bootstrap header in tendermint worker~ https://github.com/CodeChain-io/foundry/pull/29
* https://github.com/CodeChain-io/codechain/commit/cc236fd936dd352449aa4d15746e24faee43cac5 Add sync state SnapshotBody
* ~https://github.com/CodeChain-io/codechain/commit/0ba5323e86ee0db264c005166a81eb85f8a449f7 Move to SnapshotBody state after downloading the snapthot header~
* ~https://github.com/CodeChain-io/codechain/commit/abe60a324665e9c07b8fadb3fd5dbba96026c30e Import snapshot block with body~
* ~https://github.com/CodeChain-io/codechain/commit/9354d8d37dc983a86bafbc08d25e4bc86d6413f1 Update the best block after importing snapshot chunks~
* https://github.com/CodeChain-io/codechain/commit/eb6b204ce82c402df094a09dd1815ea5b0555403 Refactor block::Extension::transtition_to_full()
* ~https://github.com/CodeChain-io/codechain/commit/afcf587b8516d5f4b86048e7b53e59db79cc9fca Change sync extension to update pivot after transitioning to Full~
* ~https://github.com/CodeChain-io/codechain/commit/0c598ced1e75c191393fec2a901ead6adc1db2c3 Fix to receive peer requests from just connected nodes~
* ~https://github.com/CodeChain-io/codechain/commit/28776858b6dd07df1fac906b78df4751b5f3cfff Defer sending peer status after transitioning to full sync mode~
* ~https://github.com/CodeChain-io/codechain/commit/d8368c5f62d3bb9f27b052f4f577055efe76a218 Factor out snapshot notify~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/9ce70ad3175d8cacbbd097d4e88d2e193377e5f9 Move send_snapshot_notify() before the early return~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/ed78493d74900d242efcc94c7b6a59fa4d4843ee Defer snapshot timing by one block in Tendermint~ https://github.com/CodeChain-io/foundry/pull/19
* https://github.com/CodeChain-io/codechain/commit/d925fec3bcced18d2d3dc73e195589e52af21288 Fix snapshot block estimation in test
* ~https://github.com/CodeChain-io/codechain/commit/18f8fa778f4e315d9229d5b896760981e8543179 Introduce CurrentValidators~ https://github.com/CodeChain-io/foundry/pull/27
* ~https://github.com/CodeChain-io/codechain/commit/275a671dd8c7981fbb50c5560cb8a61db28b71a6 Get tendermint validators with CurrentValidators~ https://github.com/CodeChain-io/foundry/pull/27
* ~https://github.com/CodeChain-io/codechain/commit/f192340bf32e8c2b0a3c60ac7121255da19a68c9 Generate snapshot chunks for shard level state~ https://github.com/CodeChain-io/foundry/pull/19
* ~https://github.com/CodeChain-io/codechain/commit/8a428cbf523d32e99e795363d5f4323b11abf827 Refactor on_chunk_response~
* ~https://github.com/CodeChain-io/codechain/commit/f6283507a60fd67c4343f3726eaa5358f099fcfe Refactor sync state transition~
* ~https://github.com/CodeChain-io/codechain/commit/364fa1897a304c34cd38c21bf40263aa1a1efce2 Import shard trie chunks in sync extension~

**Comment by majecty** [comment]
Snapshot PR is merged. I checked commits left. 4 commits are not merged in Foundry. @Remagpie Do you have any reason that does not include them in the Foundry PR? 

* CodeChain-io/codechain@ef3ad4f Use binding for match clause: This commit is not included in Foundry, but it is a refactoring commit.
* CodeChain-io/codechain@cc236fd Add sync state SnapshotBody: This commit is not included in Foundry, Foundry code already has `SnapshotBody` state. It may be squashed to another commit.
https://github.com/CodeChain-io/foundr/blob/f681960a56095c8d023e572a53c6288db2955e90/sync/src/block/extension.rs#L65
* CodeChain-io/codechain@eb6b204 Refactor block::Extension::transtition_to_full(): This commit is not included in Foundry, but it is a refactoring commit.
* CodeChain-io/codechain@d925fec Fix snapshot block estimation in test: This commit is not included in Foundry, it modifies only test code.

**Comment by Remagpie** [comment]
* https://github.com/CodeChain-io/codechain/commit/ef3ad4f was not included since I thought it doesn't introduce any "feature" related to the snapshot sync. You're free to merge it if you want.
* The content of https://github.com/CodeChain-io/codechain/commit/cc236fd was included in another commit. You can see it here: https://github.com/CodeChain-io/foundry/commit/5dbe6bb2b7e8f250aeced16f4786bafb86f028f6
* https://github.com/CodeChain-io/codechain/commit/eb6b204 was discarded since it is replaced by newer logic in the later commit. See https://github.com/CodeChain-io/foundry/commit/2ab6e5470fe870f37770997ea5af01e0200e0d4a
* https://github.com/CodeChain-io/codechain/commit/d925fec was squashed into the other commit. It's included in this one: https://github.com/CodeChain-io/foundry/commit/f681960a56095c8d023e572a53c6288db2955e90

**Comment by majecty** [comment]
We ported all commits in Foundry! I'll close this issue.
