### ISSUE TITLE
Remove code related to reorganization

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/foundry#31]

**Comment by HoOngEe** [comment]
Could you let me roughly know which modules will be affected by this patch?

**Comment by majecty** [comment]
@sgkim126 Could you explain it to HoOngEe?

**Comment by sgkim126** [comment]
As you know, since CodeChain supports the re-organizable consensus, such as PoW, it has features about a branch(which is not the best chain).
For instance, you can see [`BestBlockChanged`](https://github.com/CodeChain-io/foundry/blob/master/core/src/blockchain/block_info.rs#L24), `retracted` and `omitted` field of [`ImportRoute`](https://github.com/CodeChain-io/foundry/blob/master/core/src/blockchain/route.rs#L112), and [`TreeRoute`](https://github.com/CodeChain-io/foundry/blob/master/core/src/blockchain/route.rs#L23).
There are code that uses those structures.
We can simplify them but you should keep in mind that even though Foundry only supports tendermint some blocks in db can be reverted if the block doesn't gather enough commits. However, only one level block can be reverted and the code can be much simpler than now.

**Comment by sgkim126** [comment]
I didn't check, but I think there can be a point to be optimized in the sync module.
@HoOngEe would you check it?

**Comment by HoOngEe** [comment]
@sgkim126 Ok, I forgot about it. I started working on it.

**Comment by HoOngEe** [comment]
#131 resolved some part of the issue but there may be some optimization points after removing the concept of the score(#236)
