### ISSUE TITLE
Improve FML

### ISSUE THREAD

**Issue by junha1** [CodeChain-io/foundry#314]
1. Make the macro composable. No repetition of either coding or even compile for various kinds of handle traits.
- To do this, I'm designing new way of link-time list (of used handles) composition and installation (which involves iteration)
2. Support dynamically decidable method/trait id without overhead
- Assigning the actual values is role of coordinator
3. Refactor common parts out of the macro and use generic instead. Alos make current code follow standard way of implementing proc macro.
4. Decouple port server and port client
5. Return by `Box<dyn MyHandle>` and make the macro automatically deal with it

**Comment by junha1** [comment]
FML is migrated.

**Comment by majecty** [comment]
https://github.com/CodeChain-io/baselink-rs/issues
