### ISSUE TITLE
coordinator::BlockExecutor trait must be fit into FML

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/foundry#350]
`BlockExecutor` trait in `coordinator` module is exposing the `&mut dyn SubStorageAccess`, which is a handle, in argument positions. However, current FML cannot generate compilable code for methods which include handles in arguments.

**Comment by HoOngEe** [comment]
For example, the signature of `open_block` is `fn open_block(&self, context: &dyn SubStorageAccess, header: &Header, verified_crime: &[VerifiedCrime])`.
We must implement this trait in a module with the signature `fn open_block(&self, header: &Header, verified_crime: &[VerifiedCrime])` and utilize an additional handle supporting `fn get_context() -> &dyn SubStorageAccess`. IMO the firstly wanted signature is just a composition of the latter ones and we can support it in a natural way. What do you think of it @junha1

**Comment by junha1** [comment]
@HoOngEe Tbh the first option can be supported if I take some time, but need discussion whether it's desirable.

**Comment by Byeongjee** [comment]
Since `BlockExecutor` lies between the host and the coordinator, it doesn't have to fit into FML.
What should fit into FML is SubStorageAccess-related handles that the coordinator provides to modules.
