### ISSUE TITLE
Need to return transaction hashes when transactions are injected to mempool

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/foundry#378]
Transaction hashes are identifiers of transactions. Users may need to lookup transactions by their hashes so the agreed transaction hash need be defined. I thought it is more relevant for transaction hashes to be defined by the host.

**Comment by Byeongjee** [comment]
Do you mean this? https://github.com/CodeChain-io/foundry/blob/9b41137e14ba4eeaeaab96d4a60a18b844786647/coordinator/src/types.rs#L100

**Comment by HoOngEe** [comment]
Ok. When a user send a transaction to mempool through modules, host returns the corresponding transaction hash and modules just pass it to users. Module level hash handling seems to be unnecessary.
