### ISSUE TITLE
Create and place transactions to postprocess state changes.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/foundry#385]
Some modules may want to implement postprocessing transactions: Distribute block rewards to stakeholders; elect new validators; jail lazy validators. However, for modules to create those kinds of transactions need to know what transactions would be included in the current block and what is the final state as the result of execution.
Therefore, preparing those transactions can not be achieved by a single method call `prepare_block`. I thought that the `close_block` is be the right place to deliver those transactions from modules to the host to include them in the block because all requirements are fulfilled at that context.
However, the host isn't responsible for transaction ordering so placing those transactions in the right place is impossible without an additional help from modules. Re-calling `prepare_block` after receiving additional transactions may be one possible solution but it seems inefficient.
Because creating those kind of transactions demands above requirements, additional method calls are inevitable. Do you have any better idea for the solution?

**Comment by majecty** [comment]
IMO, adding "close_block" that returns transactions is the right choice.
For the order, there should be "a place" that specifies "close_block" orders between the modules. Maybe app descriptor?

**Comment by HoOngEe** [comment]
@Byeongjee explained me about the detailed interface changes. In the changed interface, we can prepare postprocessing transactions because it accompanies execution. What I can do is implement suitable "create" functions for those transactions assuming state is ready then coordinator can invoke module functions and combine the results.
