### ISSUE TITLE
DynamicValidator implementation is incomplete in mold

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/foundry#397]
`next_block_proposer` method of the trait `ValidatorSet` have assumed that `validators` method returns the validators sorted in a desirable order so that it can just pick the next validator by the index `view`.
However, the ordering rule changed after #388 and the previous behavior can not be simulated by the `SimpleValidator` in mold which only contains `voting_power` and `public_key`. I can copy the previous logic properly to recover the behavior.

**Comment by majecty** [comment]
The behavior is changed here: https://github.com/CodeChain-io/foundry/pull/602
We will track the problem here: https://github.com/CodeChain-io/foundry/issues/603
