### ISSUE TITLE
Failures in tests

### ISSUE THREAD

**Issue by junha1** [CodeChain-io/foundry#447]
In bdbb207,

1. Travis CI
```
Dave should be a validator when deposit enough
CodeChain(117) exited with code 255, null
      1) "after each" hook for "Dave should be a validator when deposit enough"

4. Nominate new candidate
      with enough deposit, but without delegation
        ✓ should keep possible authors after a term change (13761ms)
        2) "after each" hook for "should keep possible authors after a term change"
```

2. My local machine
```
  1) Shutdown test
       Partial shutdown
         Alphas should be next validators after a complete shutdown:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/junha/Projects/foundry/test/src/e2e.dynval/2/dv.shutdown.test.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Shutdown test
       "after each" hook for "Alphas should be next validators after a complete shutdown":
     Error: Timeout period is expired while waiting connect each other
      at PromiseExpect.checkFulfilled (src/helper/promise.ts:54:19)
      at Context.<anonymous> (src/e2e.dynval/2/dv.shutdown.test.ts:303:23)
      at processImmediate (internal/timers.js:456:21)

```
in my machine

**Comment by majecty** [comment]
I've run tests in bdbb207cca04c3dde8dda411eada1e68d80ee787 and 8334a0c3e665b85740052f9a5ce22d4d8fb3a9b8 commit multiple times. All the tests succeed.

I've used the command below:
```sh
yarn mocha -r ts-node/register --timeout 10000 src/e2e.dynval/2/dv.shutdown.test.ts
yarn mocha -r ts-node/register --timeout 10000 src/e2e.dynval/1/dv.m-m\'.test.ts
```

It seems that failure occurs not frequently.

**Comment by MSNTCS** [comment]
The same failure tests happened several times in my machine using @majecty's suggested commands. I will check the logic of related implementations.

**Comment by MSNTCS** [comment]
> The same failure tests happened several times in my machine using @majecty's suggested commands. I will check the logic of related implementations. I ran tests in `bc771a4`. 

The failure seems to be because of the informer API. 
```
Thread 'main' panicked at 'Cannot listen TCP port: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', network/src/p2p/handler.rs:153
```

**Comment by MSNTCS** [comment]
@junha1 and @majecty The reason `Shutdown` tests fail is because of port conflict. @junha1 in your local machine you need to kill all process of foundry after `Shutdown` tests. It seems some processes are working after the tests got fail or pass. I could not found any reason except this.

**Comment by junha1** [comment]
So I was running multiple foundry instances? I don't remember that, tbh.

**Comment by MSNTCS** [comment]
> So I was running multiple foundry instances? I don't remember that, tbh.

I think there might be some foundry processes running in your background making port conflicts. This is what I found after testing a lot of things.

**Comment by majecty** [comment]
OK, then we need to debug the shutdown test. If we fix it this issue will be resolved.

**Comment by MSNTCS** [comment]
> OK, then we need to debug the shutdown test. If we fix it this issue will be resolved.

Did you mean the failed tests in Travis CI? Because `Shutdown`  tests seem working fine.

**Comment by majecty** [comment]
@MSNTCS You said:
> you need to kill all process of foundry after Shutdown tests. It seems some processes are working after the tests got fail or pass. I could not found any reason except this.

Shutdown test must not make processes live after the test.

**Comment by MSNTCS** [comment]
The problem was mainly because of not shouting down of running nodes in `shout down` tests. #502 fixed this issue.
