### ISSUE TITLE
Create trace APIs

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#49]
The indexer is re-calculating what a node has calculated. The reward calculation of the dynamic validator is also calculated in the indexer, which is very complicated. If CodeChain provides the Trace API, which tells what values in the state are changed for each block, it will help greatly when creating an application

* Go Ethereum's trace API [link](https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction)
* Parity's trace API [link](https://wiki.parity.io/JSONRPC-trace-module)

**Comment by kseo** [comment]
We renamed Trace API to Informer API. See #137.
