### ISSUE TITLE
jsonrpc_http_server spits out Parse(Header) error

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/foundry#52]
jsonrpc_http_server spits out the following error sometimes:
```http.worker00 jsonrpc_http_server Error serving connection: Error { kind: Parse(Header) }```

https://github.com/hyperium/hyper/blob/0867ad5c15fa52b7af3fc840ee7a1e256c469942/src/proto/h1/role.rs

There are several situations where `Parse::Header` is raised in `hyper`. We need to lower the error level of hyper to `hyper=debug` to investigate why they are failing.

**Comment by majecty** [comment]
Foundry will not use JSON RPC.
