### ISSUE TITLE
Header verification does not verify seals in the header

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#68]
In Bitcoin, creating a valid header is difficult because of the header's hash should satisfy a special rule. They use the header chain to verify the chain before receiving whole blocks.

CodeChain also has a header chain. CodeChain's header contains signatures from validators. Verifying the header is impossible because the validator set change is not described in the header. The lack of verification allows DoS attacks on the header sync.

We should remove the header chain or make the header chain verifiable. We may add validator set changes in the header to make it verifiable.

**Comment by majecty** [comment]
I'll introduce `SyncHeader` struct. The header sync will use `SyncHeader` instead of `Header`.

```rust
struct SyncHeader {
  header: Header,
  validator_set: Either<ValidatorSet, NotModified>,
  precommits: Vec<Signature>
}
```

* The validator_set will contain the validator set information only when the validator set is changed.

## Expected results

* We can verify a header with the previous header.
* The size of the header used in the header sync became twice. If we will aggregate the precommits, it is neglectable

**Comment by majecty** [comment]
Proposal B:

I'll introduce SyncHeader struct. The header sync will use SyncHeader instead of Header.

struct SyncHeader {
  header: Header,
  validator_set: Option<ValidatorSet>,
}

    The validator_set will contain the validator set information only when the validator set is changed.

Expected results

    We can verify a header with the next header.
    The size of the header will not be changed much. In a term change header or double vote detected header will have additional "validator_set" information.

**Comment by sgkim126** [comment]
I think both proposals can be easily deceived because the validator set in the SyncHeader is not verified.
I think the sync header scheme must have a way to confirm the validator set, but I cannot find it yet.

**Comment by sgkim126** [comment]
I talked with @majecty. It will work because the Header already has the hash of the next validators. We decided to implement the proposal B. The proposal A can fix the issue that needs the next header to verify the current header, but it will be discussed in the other issue in next time.

**Comment by majecty** [comment]
Having a current validator set has a problem.

1. SyncHeader has the current validator set
We can't verify signatures in the header. To verify the signatures, we need the previous block's validator set.

```rust
struct SyncHeader {
  // header.number == n
  header: Header,
  // the validator set who created block n
  validator_set: Option<ValidatorSet>,
}
```

2. SyncHeader has the previous validator set
We can verify signatures with the validator set. However, to verify the validator set, we should read the prev-prev header's next_validator_set_hash. It seems awkward.

```rust
struct SyncHeader {
  // header.number == n
  header: Header,
  // the validator set who created block n - 1
  prev_validator_set: Option<ValidatorSet>,
}
```

@sgkim126 IMO the number two is better since it makes easier to verify a `SyncHeader` struct.

**Comment by sgkim126** [comment]
I agree with you. The second one has no problem since the sync extension always downloads the parent header before validating the next header.

**Comment by majecty** [comment]
We added header verification here: https://github.com/CodeChain-io/foundry/pull/386
