### ISSUE TITLE
Remove Assets

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#7]
Each module will define its assets. We don't need to provide a general asset mechanism in Foundry.

- [x] Remove asset-related RPCs
- [x] Remove asset-related transactions
- [x] Remove the types related to asset from `types`
    - TransferAsset
        - struct AssetTransferInput
        - struct AssetOutPoint
        - struct AssetTransferOutput
    - struct AssetMintOutput    
    - struct AssetWrapCCCOutput
- [x] Remove assets from MemPoolMinFees in `miner` and `rpc types`
- [x] Remove assets from the e2e tests
- [x] Modify the e2e tests

**Comment by somniumism** [comment]
PR #246 resolved this issue.

**Comment by HoOngEe** [comment]
Let's remove the `Asset` also from documents, test macro, json scheme texts
