### ISSUE TITLE
Returning Arc<Self> should be refactored

### ISSUE THREAD

**Issue by foriequal0** [CodeChain-io/foundry#77]
We can easily find following pattern in our codebase.
```rust
#[cfg_attr(feature = "cargo-clippy", allow(clippy::new_ret_no_self))]
pub fn new(...) -> Arc<Self>
```
I think we can adopt following pattern from rust std libraries.
https://doc.rust-lang.org/src/std/io/stdio.rs.html#145-147
https://doc.rust-lang.org/src/std/thread/mod.rs.html#1018-1020
And also, abusing ```Weak``` a little bit, we can make Self as Arc-aware.
```rust
struct Outer {
  inner: Arc<Inner>
}

struct Inner {
  _ref: Weak<Inner>
}

impl Outer {
  fn new() -> Outer {
    let mut inner = Arc::new(Inner{ _ref: Weak::new() });
    inner._ref = inner;
    inner
  }
}

impl Inner {
  fn register_to_something(&self, ext: &Extension) {
    ext.register(self._ref.upgrade().unwrap());
  }
}
```
 ```_self: Weak<Self>```, we can

**Comment by Byeongjee** [comment]
@sgkim126  I just found this issue while searching for thread stuff.
I don't have a background on Rust history so I'm not perfectly sure, but it seems that this can be closed now, is it correct?

**Comment by sgkim126** [comment]
@Byeongjee Yes, I think we can close it. The standard library also has `new` method that returns the type that contains `Self` and the clippy rule fixed.
