### ISSUE TITLE
Integrate Mergify

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#87]
CodeChain-io/CodeChain project makes the Mergify bot automatically merge a PR if the PR is reviewed and all tests are passed. We need it in this repo.

**Comment by majecty** [comment]
I enabled Mergify.

**Comment by majecty** [comment]
It is not working.

**Comment by MSNTCS** [comment]
@majecty Can you list what you have done for this?

**Comment by majecty** [comment]
I don't remember well but, I think I enabled Mergify in GitHub config.
![image](https://user-images.githubusercontent.com/709900/92542406-9f91ee00-f283-11ea-8e86-337f3f1d9086.png)

**Comment by MSNTCS** [comment]
> I don't remember well but, I think I enabled Mergify in GitHub config.
> ![image](https://user-images.githubusercontent.com/709900/92542406-9f91ee00-f283-11ea-8e86-337f3f1d9086.png)

It seems mergify works. look at this #236 and it is merged with mergify.
<img width="1000" alt="Screen Shot 2020-09-09 at 10 47 05 AM" src="https://user-images.githubusercontent.com/50092326/92545013-39f53000-f28a-11ea-8539-8506dddf4138.png">

**Comment by MSNTCS** [comment]
@majecty I checked mergify documentation and everything seems alright and I think there is one working example. Should I close this issue?

**Comment by majecty** [comment]
@MSNTCS OK.
